name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

defaults:
  run:
    shell: nix develop --command bash -e {0}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: NixOS/nix-installer-action@main

      - name: Setup Nix cache (hestia)
        uses: Mic92/hestia/action@main

      - name: Run GoReleaser
        run: goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
